"""Researched folk & roots music festivals with web-based application processes.

Compiled from public festival websites and application pages (June 2026).
Dates marked "approx" recur on a similar window each year; always verify on the
festival's own application page (``application_url``) before relying on them.

Each festival carries a ``form_fields`` schema describing its online application
form. The mapping engine (``app.mapping``) uses ``maps_to`` to pull from the
user's master assets and ``transform`` to decide whether a field is copied
verbatim or rewritten/reshaped by the local LLM to satisfy length and tone
constraints.
"""

from __future__ import annotations

# --- Standard application-form field builder -------------------------------
#
# Most folk/roots festivals ask for the same shape of information. We build a
# realistic field list from this template and let each festival override the
# bits that genuinely differ (bio word limits, whether a fee/availability is
# requested, genre options, etc.).


def make_fields(
    *,
    bio_words: int = 150,
    one_liner_words: int = 25,
    ask_short_bio: bool = True,
    ask_video: bool = True,
    ask_spotify: bool = True,
    ask_press: bool = False,
    ask_fee: bool = False,
    ask_availability: bool = True,
    ask_members: bool = True,
    bio_label: str = "Artist biography",
    genre_options=None,
    extra=None,
):
    fields = [
        {
            "key": "act_name",
            "label": "Act / artist name",
            "type": "text",
            "required": True,
            "maps_to": "act_name",
            "transform": "verbatim",
        },
        {
            "key": "contact_name",
            "label": "Primary contact name",
            "type": "text",
            "required": True,
            "maps_to": "contact_name",
            "transform": "verbatim",
        },
        {
            "key": "email",
            "label": "Contact email",
            "type": "email",
            "required": True,
            "maps_to": "email",
            "transform": "verbatim",
        },
        {
            "key": "phone",
            "label": "Contact phone",
            "type": "text",
            "required": False,
            "maps_to": "phone",
            "transform": "verbatim",
        },
        {
            "key": "based_in",
            "label": "Where are you based?",
            "type": "text",
            "required": True,
            "maps_to": "based_in",
            "transform": "verbatim",
        },
        {
            "key": "genre",
            "label": "Genre / style",
            "type": "select" if genre_options else "text",
            "options": genre_options,
            "required": True,
            "maps_to": "genre",
            "transform": "rewrite" if genre_options else "verbatim",
            "help": "Pick the closest match" if genre_options else None,
        },
    ]

    if ask_members:
        fields.append(
            {
                "key": "members",
                "label": "Number of performers on stage",
                "type": "number",
                "required": True,
                "maps_to": "members",
                "transform": "verbatim",
            }
        )

    fields.append(
        {
            "key": "artist_bio",
            "label": bio_label,
            "type": "textarea",
            "required": True,
            "maps_to": "bio",
            "transform": "rewrite",
            "max_words": bio_words,
            "help": f"Maximum {bio_words} words.",
        }
    )

    if ask_short_bio:
        fields.append(
            {
                "key": "one_liner",
                "label": "One-line description / tagline",
                "type": "text",
                "required": True,
                "maps_to": "one_liner",
                "transform": "rewrite",
                "max_words": one_liner_words,
                "help": f"A punchy single sentence (≈{one_liner_words} words).",
            }
        )

    fields += [
        {
            "key": "website",
            "label": "Website",
            "type": "url",
            "required": False,
            "maps_to": "website",
            "transform": "verbatim",
        },
        {
            "key": "facebook",
            "label": "Facebook page",
            "type": "url",
            "required": False,
            "maps_to": "facebook",
            "transform": "verbatim",
        },
        {
            "key": "instagram",
            "label": "Instagram",
            "type": "url",
            "required": False,
            "maps_to": "instagram",
            "transform": "verbatim",
        },
    ]

    if ask_video:
        fields.append(
            {
                "key": "youtube",
                "label": "Live performance video (YouTube/Vimeo)",
                "type": "url",
                "required": True,
                "maps_to": "youtube",
                "transform": "verbatim",
                "help": "A link to recent live footage is usually essential.",
            }
        )
    if ask_spotify:
        fields.append(
            {
                "key": "spotify",
                "label": "Spotify / Bandcamp / streaming",
                "type": "url",
                "required": False,
                "maps_to": "spotify",
                "transform": "verbatim",
            }
        )

    fields.append(
        {
            "key": "epk",
            "label": "EPK / press kit link",
            "type": "url",
            "required": False,
            "maps_to": "epk",
            "transform": "verbatim",
        }
    )

    if ask_press:
        fields.append(
            {
                "key": "press_quotes",
                "label": "Press quotes / reviews",
                "type": "textarea",
                "required": False,
                "maps_to": "press_quotes",
                "transform": "rewrite",
                "max_words": 80,
            }
        )

    fields.append(
        {
            "key": "photos",
            "label": "Promotional photos",
            "type": "files",
            "required": True,
            "maps_to": "photo_urls",
            "transform": "list",
            "help": "Provide high-resolution press photo links/files.",
        }
    )

    if ask_availability:
        fields.append(
            {
                "key": "availability",
                "label": "Availability / scheduling notes",
                "type": "textarea",
                "required": False,
                "maps_to": "availability",
                "transform": "verbatim",
            }
        )
    if ask_fee:
        fields.append(
            {
                "key": "fee",
                "label": "Fee expectation",
                "type": "text",
                "required": False,
                "maps_to": "fee",
                "transform": "verbatim",
            }
        )

    if extra:
        fields += extra

    # Drop None helper/options keys to keep the schema tidy.
    for f in fields:
        for k in ("help", "options"):
            if k in f and f[k] is None:
                del f[k]
    return fields


FOLK = ["folk"]

# --- The festival database -------------------------------------------------
# region: Oceania (Australia / NZ), Europe, North America

FESTIVALS = [
    # ===================== AUSTRALIA =====================
    {
        "name": "National Folk Festival",
        "url": "https://www.folkfestival.org.au/",
        "application_url": "https://www.folkfestival.org.au/artistapplications",
        "location": "Canberra, ACT",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "world", "celtic", "acoustic"],
        "festival_month": "April (Easter)",
        "next_edition": "2–6 April 2026",
        "application_window": "Applications typically open mid-year and close around September for the following Easter.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "closed",
        "form_platform": "FestivalPro",
        "headliners": ["Rotating program of Australian & international folk/roots acts"],
        "notes": "Australia's flagship folk festival, held over the Easter long weekend at Exhibition Park (EPIC). Applications are submitted through a FestivalPro form.",
        "source_url": "https://nff.festivalpro.com/form/dQgZJumJVdxDtcvAENZv/51",
        "form_fields": make_fields(bio_words=150, ask_press=True),
    },
    {
        "name": "Woodford Folk Festival",
        "url": "https://woodfordfolkfestival.com/",
        "application_url": "https://woodfordfolkfestival.com/get-involved/artists-and-presenters/",
        "location": "Woodford, QLD",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "world", "roots", "spoken word", "circus"],
        "festival_month": "27 Dec – 1 Jan",
        "next_edition": "2026/27 (27 Dec 2026 – 1 Jan 2027)",
        "application_window": "Expression of Interest opened 30 Jan 2026, closed 31 Mar 2026 for 2026/27. Reopens ~Jan 2027 for 2027/28.",
        "application_opens": "2026-01-30",
        "application_closes": "2026-03-31",
        "application_status": "closed",
        "form_platform": "JotForm",
        "headliners": ["Broad multi-arts program (music, storytelling, dance, comedy, circus)"],
        "notes": "One of the largest gatherings of its kind in Australia. Artists & presenters submit an EOI via JotForm; proof of Public Liability Insurance required at contracting.",
        "source_url": "https://form.jotform.com/251487815258871",
        "form_fields": make_fields(
            bio_words=200,
            ask_press=True,
            bio_label="Artist/presenter biography",
            extra=[
                {
                    "key": "performance_type",
                    "label": "Type of offering (music, workshop, talk, dance, etc.)",
                    "type": "text",
                    "required": True,
                    "maps_to": "genre",
                    "transform": "verbatim",
                }
            ],
        ),
    },
    {
        "name": "Port Fairy Folk Festival",
        "url": "https://portfairyfolkfestival.com/",
        "application_url": "https://portfairyfolkfestival.com/applications/",
        "location": "Port Fairy, VIC",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "world", "blues", "celtic"],
        "festival_month": "March (Labour Day long weekend)",
        "next_edition": "March 2027",
        "application_window": "Artist applications for 2027 have closed; the window generally runs mid-year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "closed",
        "form_platform": "Own site form",
        "headliners": ["~100 national & international artists booked each year"],
        "notes": "Part of the summer 'folk trail' (with Cygnet and Illawarra) that draws high-profile overseas artists. Accepts music, theatre, spoken word, dance and comedy.",
        "source_url": "https://portfairyfolkfestival.com/applications/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Illawarra Folk Festival",
        "url": "https://illawarrafolkfestival.com.au/",
        "application_url": "https://folkfednsw.org.au/",
        "location": "Bulli, NSW",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "world", "acoustic"],
        "festival_month": "January",
        "next_edition": "January 2027",
        "application_window": "Performer applications (EOI) usually open mid-year via the Folk Federation of NSW.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "EOI form",
        "headliners": ["Strong grassroots & emerging-artist focus"],
        "notes": "Established in 1985 by the Illawarra Folk Club; run by the Folk Federation of NSW. Performer applications handled via an online EOI form.",
        "source_url": "https://folkfednsw.org.au/2025-illawarra-folk-festival-performer-applications-are-open/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Cygnet Folk Festival",
        "url": "https://www.cygnetfolkfestival.org/",
        "application_url": "https://www.cygnetfolkfestival.org/about/faqs",
        "location": "Cygnet, TAS",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "world", "acoustic"],
        "festival_month": "January",
        "next_edition": "January 2027",
        "application_window": "Apply via the online application form on the festival website; buskers also welcome.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Part of the Tasmanian leg of the summer folk trail"],
        "notes": "Intimate festival in the Huon Valley. Applications to perform are made through the online form; busking guidelines published separately.",
        "source_url": "https://www.cygnetfolkfestival.org/about/faqs?tag=Performer+application",
        "form_fields": make_fields(bio_words=120),
    },
    {
        "name": "Fairbridge Festival",
        "url": "https://fairbridgefestival.com.au/",
        "application_url": "https://fairbridgefestival.com.au/",
        "location": "Pinjarra, WA",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "world", "roots", "blues"],
        "festival_month": "April",
        "next_edition": "April 2027",
        "application_window": "Artist applications have historically opened in August and closed late September.",
        "application_opens": "2026-08-01",
        "application_closes": "2026-09-27",
        "application_status": "upcoming",
        "form_platform": "Own site form / email",
        "headliners": ["Strong youth-arts and emerging-artist programs"],
        "notes": "WA's largest folk & world music festival, held at the historic Fairbridge Village. Contact artists@fairbridgefestival.com.au for application details.",
        "source_url": "https://www.propel.org.au/news-and-opportunities/fairbridge-festival-eoi",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Nannup Music Festival",
        "url": "https://www.nannupmusicfestival.org/",
        "application_url": "https://www.nannupmusicfestival.org/the-festival/",
        "location": "Nannup, WA",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "indie", "world", "blues"],
        "festival_month": "Feb/Mar (long weekend)",
        "next_edition": "26 Feb – 1 Mar 2027",
        "application_window": "Expressions of Interest open ahead of each edition; supported by the WA Contemporary Music Fund.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Eclectic mix of live acts in WA's South West"],
        "notes": "Set in the small town of Nannup over the March long weekend.",
        "source_url": "https://www.nannupmusicfestival.org/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Blue Mountains Music Festival",
        "url": "https://www.bmff.org.au/",
        "application_url": "https://www.bmff.org.au/",
        "location": "Katoomba, NSW",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "blues", "world"],
        "festival_month": "March",
        "next_edition": "March 2027",
        "application_window": "Performer EOIs usually open in the second half of the year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Folk, roots & blues across the Blue Mountains"],
        "notes": "Held in Katoomba in the heart of the Blue Mountains; formerly 'Blue Mountains Folk Festival'.",
        "source_url": "https://www.bmff.org.au/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Mullum Music Festival",
        "url": "https://www.mullummusicfestival.com/",
        "application_url": "https://www.mullummusicfestival.com/",
        "location": "Mullumbimby, NSW",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "indie", "world", "soul"],
        "festival_month": "November",
        "next_edition": "November 2026",
        "application_window": "Artist submissions generally open mid-year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Town-wide festival across venues in Mullumbimby"],
        "notes": "A 'town becomes the festival' event in the NSW Northern Rivers.",
        "source_url": "https://www.mullummusicfestival.com/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Yackandandah Folk Festival",
        "url": "https://yackfolkfestival.com/",
        "application_url": "https://yackfolkfestival.com/apply/perform/",
        "location": "Yackandandah, VIC",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "old-time", "world", "bluegrass", "americana", "blues", "jazz"],
        "festival_month": "March",
        "next_edition": "19–21 March 2027",
        "application_window": "Performer applications for 2027 open in July 2026.",
        "application_opens": "2026-07-01",
        "application_closes": None,
        "application_status": "upcoming",
        "form_platform": "Own site form",
        "headliners": ["Traditional folk, old-timey, world, bluegrass & Americana"],
        "notes": "Community-run festival in Victoria's High Country with a broad definition of folk.",
        "source_url": "https://www.yackfolkfestival.com/join-in/perform/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Tamworth Country Music Festival",
        "url": "https://www.tcmf.com.au/",
        "application_url": "https://www.tcmf.com.au/",
        "location": "Tamworth, NSW",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["country", "americana", "roots", "bluegrass"],
        "festival_month": "January",
        "next_edition": "16–25 January 2026",
        "application_window": "Artist registrations and talent competitions open in the second half of the prior year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site registration",
        "headliners": ["Troy Cassar-Daley", "Fanny Lumsden", "Dylan Wright"],
        "notes": "Australia's biggest country music festival; runs free and ticketed shows plus talent competitions for emerging and established artists.",
        "source_url": "https://www.tcmf.com.au/news/2026-first-artist-announce",
        "form_fields": make_fields(bio_words=150, genre_options=["Traditional country", "Contemporary country", "Americana", "Bluegrass", "Country rock", "Other"]),
    },
    {
        "name": "Gympie Music Muster",
        "url": "https://www.muster.com.au/",
        "application_url": "https://www.muster.com.au/",
        "location": "Amamoor, QLD",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["country", "blues", "roots", "folk"],
        "festival_month": "August",
        "next_edition": "August 2026",
        "application_window": "Artist applications generally open in the first half of the year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Kasey Chambers", "Daryl Braithwaite", "Casey Barnes", "Adam Harvey"],
        "notes": "Four-day blues, roots and country festival in the Amamoor Creek State Forest; proceeds support charity.",
        "source_url": "https://www.muster.com.au/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Queenscliff Music Festival",
        "url": "https://qmf.net.au/",
        "application_url": "https://qmf.net.au/",
        "location": "Queenscliff, VIC",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["roots", "indie", "folk", "world", "soul"],
        "festival_month": "November",
        "next_edition": "27–29 November 2026",
        "application_window": "Artist submissions generally open mid-year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Coastal festival mixing established and emerging acts"],
        "notes": "Held on the Bellarine Peninsula by the sea each November.",
        "source_url": "https://qmf.net.au/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Maleny Music Festival",
        "url": "https://www.malenymusicfestival.com/",
        "application_url": "https://www.malenymusicfestival.com/",
        "location": "Maleny, QLD",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "celtic", "blues", "americana", "world"],
        "festival_month": "November",
        "next_edition": "November 2026",
        "application_window": "Volunteer-run; EOIs open ahead of each November event.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Folk, traditional Irish, blues & Americana"],
        "notes": "Community, volunteer-run festival at the Maleny Showgrounds in the Sunshine Coast hinterland.",
        "source_url": "https://www.malenymusicfestival.com/",
        "form_fields": make_fields(bio_words=120),
    },
    {
        "name": "Majors Creek Festival (The Stockade)",
        "url": "https://www.majorscreekfestival.com.au/",
        "application_url": "https://www.majorscreekfestival.com.au/",
        "location": "Majors Creek, NSW",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "world", "acoustic"],
        "festival_month": "November",
        "next_edition": "November 2026",
        "application_window": "Performer EOIs open in the months before the November event.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Boutique folk & roots near Braidwood/Canberra"],
        "notes": "Small, well-regarded festival in the village of Majors Creek in the NSW Southern Tablelands.",
        "source_url": "https://www.majorscreekfestival.com.au/",
        "form_fields": make_fields(bio_words=120),
    },
    {
        "name": "Newstead Live",
        "url": "https://www.newsteadlive.com/",
        "application_url": "https://www.newsteadlive.com/",
        "location": "Newstead, VIC",
        "country": "Australia",
        "region": "Oceania",
        "genres": ["folk", "roots", "acoustic", "world"],
        "festival_month": "Late January",
        "next_edition": "January 2027",
        "application_window": "Performer applications open in the second half of the year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Awards an annual 'Artist of the Year'"],
        "notes": "Village festival in central Victoria's goldfields region.",
        "source_url": "https://www.newsteadlive.com/",
        "form_fields": make_fields(bio_words=150),
    },

    # ===================== NEW ZEALAND =====================
    {
        "name": "WOMAD Aotearoa",
        "url": "https://womad.co.nz/",
        "application_url": "https://womad.co.nz/info/apply/",
        "location": "New Plymouth, Taranaki",
        "country": "New Zealand",
        "region": "Oceania",
        "genres": ["world", "roots", "folk", "global"],
        "festival_month": "March",
        "next_edition": "March 2027",
        "application_window": "Artist applications for the next festival open in late August.",
        "application_opens": "2026-08-25",
        "application_closes": None,
        "application_status": "upcoming",
        "form_platform": "Own site form",
        "headliners": ["World/global music program in the Bowl of Brooklands"],
        "notes": "The NZ edition of the global WOMAD series, run by the Taranaki Arts Festival Trust (TAFT).",
        "source_url": "https://womad.co.nz/info/apply/",
        "form_fields": make_fields(bio_words=200, ask_press=True, genre_options=["World", "Folk/traditional", "Roots", "Fusion", "Electronic/global", "Other"]),
    },
    {
        "name": "Auckland Folk Festival",
        "url": "https://www.aucklandfolkfestival.co.nz/",
        "application_url": "https://www.aucklandfolkfestival.co.nz/",
        "location": "Kumeu, Auckland",
        "country": "New Zealand",
        "region": "Oceania",
        "genres": ["folk", "roots", "acoustic", "world", "celtic"],
        "festival_month": "January (Auckland Anniversary weekend)",
        "next_edition": "January 2027",
        "application_window": "Guest/performer applications for 2027 are open now.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "open",
        "form_platform": "Own site form",
        "headliners": ["NZ's largest folk festival"],
        "notes": "Held annually over three days on Auckland Anniversary weekend in January.",
        "source_url": "https://www.facebook.com/aucklandfolkfest/posts/1554083476719439/",
        "form_fields": make_fields(bio_words=150),
    },
    {
        "name": "Whare Flat Folk Festival",
        "url": "https://www.whareflat.org.nz/",
        "application_url": "https://www.whareflat.org.nz/-2",
        "location": "Waiora Scout Camp, near Dunedin",
        "country": "New Zealand",
        "region": "Oceania",
        "genres": ["folk", "celtic", "old-time", "bluegrass", "world"],
        "festival_month": "30 Dec – 2 Jan",
        "next_edition": "30 Dec 2026 – 2 Jan 2027",
        "application_window": "Artist applications are open via the festival website.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "open",
        "form_platform": "Own site form",
        "headliners": ["Celtic, local waiata, American old-time & bluegrass"],
        "notes": "Set in native bush near Dunedin. Preference given to performers on site for the whole festival.",
        "source_url": "https://www.whareflat.org.nz/-2",
        "form_fields": make_fields(bio_words=150, ask_availability=True),
    },
    {
        "name": "Wellington Folk Festival",
        "url": "https://www.wellingtonfolkfestival.org.nz/",
        "application_url": "https://www.wellingtonfolkfestival.org.nz/",
        "location": "Wellington",
        "country": "New Zealand",
        "region": "Oceania",
        "genres": ["folk", "acoustic", "celtic", "world"],
        "festival_month": "Labour weekend (October)",
        "next_edition": "October 2026",
        "application_window": "Performer applications open mid-year.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Community folk festival over Labour weekend"],
        "notes": "Long-running folk camp/festival run by the Wellington folk community.",
        "source_url": "https://www.wellingtonfolkfestival.org.nz/",
        "form_fields": make_fields(bio_words=120),
    },

    # ===================== UNITED KINGDOM / EUROPE =====================
    {
        "name": "Cambridge Folk Festival",
        "url": "https://www.cambridgelive.org.uk/folk-festival",
        "application_url": "https://www.cambridgelive.org.uk/folk-festival",
        "location": "Cherry Hinton Hall, Cambridge, UK",
        "country": "United Kingdom",
        "region": "Europe",
        "genres": ["folk", "roots", "world", "americana"],
        "festival_month": "Late July / early August",
        "next_edition": "Summer 2026",
        "application_window": "Run by Cambridge Live; submissions accepted via the festival website.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["One of the world's longest-running folk festivals (since 1965)"],
        "notes": "Iconic UK folk festival with a broad roots/world program.",
        "source_url": "https://www.visitcambridge.org/event/cambridge-folk-festival-2024/",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },
    {
        "name": "Shrewsbury Folk Festival",
        "url": "https://shrewsburyfolkfestival.co.uk/",
        "application_url": "https://shrewsburyfolkfestival.co.uk/about/artist-application/",
        "location": "West Mid Showground, Shrewsbury, UK",
        "country": "United Kingdom",
        "region": "Europe",
        "genres": ["folk", "roots", "world", "acoustic"],
        "festival_month": "August bank holiday",
        "next_edition": "28–31 August 2026",
        "application_window": "2026 is fully programmed; applications to play 2027 open after the 2026 festival.",
        "application_opens": "2026-09-01",
        "application_closes": None,
        "application_status": "upcoming",
        "form_platform": "Own site form",
        "headliners": ["Top-tier UK and international folk acts"],
        "notes": "One of the UK's leading folk festivals; dedicated artist application page on its website.",
        "source_url": "https://shrewsburyfolkfestival.co.uk/about/artist-application/",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },
    {
        "name": "Celtic Connections",
        "url": "https://www.celticconnections.com/",
        "application_url": "https://www.celticconnections.com/",
        "location": "Glasgow, Scotland, UK",
        "country": "United Kingdom",
        "region": "Europe",
        "genres": ["celtic", "folk", "world", "roots", "traditional"],
        "festival_month": "January",
        "next_edition": "January 2027",
        "application_window": "Programmed by the festival; artist enquiries via the website.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Europe's largest winter roots & folk festival"],
        "notes": "Glasgow's celebration of Celtic, world, traditional and folk music every January.",
        "source_url": "https://scotland.britishcouncil.org/programmes/arts/celtic-connections",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },
    {
        "name": "Tønder Festival",
        "url": "https://tf.dk/en/",
        "application_url": "https://tf.dk/en/",
        "location": "Tønder, Denmark",
        "country": "Denmark",
        "region": "Europe",
        "genres": ["folk", "roots", "americana", "world"],
        "festival_month": "Late August",
        "next_edition": "August 2026",
        "application_window": "International folk/roots festival; submissions via the festival website.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Major European folk & roots program"],
        "notes": "One of northern Europe's most important folk festivals, running since 1975.",
        "source_url": "https://tf.dk/en/",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },

    # ===================== NORTH AMERICA =====================
    {
        "name": "Folk Alliance International (Official Showcases)",
        "url": "https://www.folk.org/",
        "application_url": "https://www.folk.org/conference/official-showcases",
        "location": "Rotating North American host city",
        "country": "United States",
        "region": "North America",
        "genres": ["folk", "roots", "americana", "world", "traditional"],
        "festival_month": "February (conference)",
        "next_edition": "FAI 2027 Conference",
        "application_window": "Official Showcase applications open ahead of the annual conference; application fee applies (FAI members 50% off).",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site / OpenWater",
        "headliners": ["Largest gathering of folk musicians & industry worldwide"],
        "notes": "Official Showcase artists are chosen via application to perform for agents, DJs, promoters, labels and presenters. Open to artists worldwide, any language.",
        "source_url": "https://www.folk.org/conference/official-showcases",
        "form_fields": make_fields(bio_words=200, ask_press=True, ask_fee=False, genre_options=["Folk", "Americana", "Roots", "World/Global", "Bluegrass", "Singer-songwriter", "Traditional", "Other"]),
    },
    {
        "name": "Newport Folk Festival",
        "url": "https://newportfolk.org/",
        "application_url": "https://newportfolk.org/",
        "location": "Fort Adams State Park, Newport, RI, USA",
        "country": "United States",
        "region": "North America",
        "genres": ["folk", "roots", "americana", "indie"],
        "festival_month": "July",
        "next_edition": "24–26 July 2026",
        "application_window": "Largely curated/invited; submissions and enquiries via the website.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Legendary US folk festival (since 1959)"],
        "notes": "Historic festival famous for landmark performances; highly curated lineup.",
        "source_url": "https://newportfolk.org/",
        "form_fields": make_fields(bio_words=150, ask_press=True),
    },
    {
        "name": "Vancouver Folk Music Festival",
        "url": "https://thefestival.bc.ca/",
        "application_url": "https://thefestival.bc.ca/",
        "location": "Jericho Beach Park, Vancouver, BC, Canada",
        "country": "Canada",
        "region": "North America",
        "genres": ["folk", "roots", "world", "indie"],
        "festival_month": "July",
        "next_edition": "17–19 July 2026",
        "application_window": "Artist submissions accepted via the festival website ahead of programming.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Billy Bragg", "Hazlett", "Local & international folk/roots"],
        "notes": "Long-running festival on the beach in Vancouver mixing legends with breakout and local artists.",
        "source_url": "https://thefestival.bc.ca/2026-artists/",
        "form_fields": make_fields(bio_words=150, ask_press=True),
    },
    {
        "name": "Winnipeg Folk Festival",
        "url": "https://www.winnipegfolkfestival.ca/",
        "application_url": "https://www.winnipegfolkfestival.ca/lineup/performers/",
        "location": "Birds Hill Provincial Park, Winnipeg, MB, Canada",
        "country": "Canada",
        "region": "North America",
        "genres": ["folk", "roots", "world", "americana"],
        "festival_month": "July",
        "next_edition": "July 2026",
        "application_window": "Performer submissions open annually in the fall.",
        "application_opens": "2026-09-01",
        "application_closes": None,
        "application_status": "upcoming",
        "form_platform": "Own site form (Performer Submissions)",
        "headliners": ["One of North America's premier folk festivals (since 1974)"],
        "notes": "Submissions handled through a dedicated Performer Submissions process; see PDF guidelines on the site.",
        "source_url": "https://www.winnipegfolkfestival.ca/wp-content/uploads/Performer-Submissions.pdf",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },
    {
        "name": "Regina Folk Festival",
        "url": "https://reginafolkfestival.com/",
        "application_url": "https://reginafolkfestival.com/artist-submissions",
        "location": "Victoria Park, Regina, SK, Canada",
        "country": "Canada",
        "region": "North America",
        "genres": ["folk", "roots", "world", "indie"],
        "festival_month": "August",
        "next_edition": "August 2026",
        "application_window": "Artist submissions accepted via a dedicated page on the festival site.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Downtown Regina folk & roots festival"],
        "notes": "Community-rooted festival with a dedicated artist-submissions page.",
        "source_url": "https://reginafolkfestival.com/artist-submissions",
        "form_fields": make_fields(bio_words=150, ask_press=True),
    },
    {
        "name": "Folk Music Canada Conference (Showcases)",
        "url": "https://www.folkcanada.com/",
        "application_url": "https://www.folkcanada.com/2026-showcase-application-form",
        "location": "Rotating Canadian host city",
        "country": "Canada",
        "region": "North America",
        "genres": ["folk", "roots", "traditional", "world"],
        "festival_month": "Annual conference",
        "next_edition": "2026 Conference",
        "application_window": "Showcase applications open ahead of the conference; 2026 official showcase deadline was 30 January 2026.",
        "application_opens": None,
        "application_closes": "2026-01-30",
        "application_status": "closed",
        "form_platform": "Own site form",
        "headliners": ["Canada's largest folk/roots/traditional industry gathering"],
        "notes": "Open to artists at any career stage, from anywhere in the world, performing in any language.",
        "source_url": "https://www.folkcanada.com/2026-showcase-application-form",
        "form_fields": make_fields(bio_words=200, ask_press=True),
    },
    {
        "name": "Kerrville Folk Festival (New Folk Competition)",
        "url": "https://www.kerrvillefolkfestival.org/",
        "application_url": "https://www.kerrvillefolkfestival.org/about/",
        "location": "Quiet Valley Ranch, Kerrville, TX, USA",
        "country": "United States",
        "region": "North America",
        "genres": ["folk", "singer-songwriter", "americana", "roots"],
        "festival_month": "May / June",
        "next_edition": "May–June 2026",
        "application_window": "The Grassy Hill New Folk Competition for Emerging Songwriters accepts entries each year (32 finalists chosen from ~800).",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Renowned New Folk songwriting competition (since 1972)"],
        "notes": "Songwriter-focused festival; the New Folk Competition is a major launchpad for emerging songwriters. Submit two original songs.",
        "source_url": "https://www.kerrvillefolkfestival.org/about/",
        "form_fields": make_fields(
            bio_words=150,
            ask_members=False,
            extra=[
                {
                    "key": "song_one",
                    "label": "Original song #1 (link)",
                    "type": "url",
                    "required": True,
                    "maps_to": "youtube",
                    "transform": "verbatim",
                },
                {
                    "key": "song_two",
                    "label": "Original song #2 (link)",
                    "type": "url",
                    "required": True,
                    "maps_to": "spotify",
                    "transform": "verbatim",
                },
            ],
        ),
    },
    {
        "name": "Telluride Bluegrass Festival (Band Contest)",
        "url": "https://bluegrass.com/telluride",
        "application_url": "https://bluegrass.com/telluride",
        "location": "Telluride, CO, USA",
        "country": "United States",
        "region": "North America",
        "genres": ["bluegrass", "folk", "americana", "roots"],
        "festival_month": "June",
        "next_edition": "June 2026",
        "application_window": "The Telluride Band Contest accepts entries ahead of the festival.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own site form",
        "headliners": ["Punch Brothers", "Sam Bush Band", "Greensky Bluegrass", "Larkin Poe"],
        "notes": "Iconic bluegrass festival in the San Juan Mountains; the Band Contest is a celebrated path for emerging bands.",
        "source_url": "https://www.telluride.com/event/telluride-bluegrass-festival/",
        "form_fields": make_fields(bio_words=150, genre_options=["Bluegrass", "Progressive bluegrass", "Old-time", "Americana", "Folk", "Other"]),
    },
    {
        "name": "SXSW (Showcasing Artist Applications)",
        "url": "https://www.sxsw.com/",
        "application_url": "https://www.sxsw.com/apply/showcase-applications/",
        "location": "Austin, TX, USA",
        "country": "United States",
        "region": "North America",
        "genres": ["all genres", "indie", "folk", "roots", "world"],
        "festival_month": "March",
        "next_edition": "March 2027",
        "application_window": "Showcasing Artist applications open in the second half of the year for the following March.",
        "application_opens": None,
        "application_closes": None,
        "application_status": "seasonal",
        "form_platform": "Own platform",
        "headliners": ["The world's best-known music showcase festival"],
        "notes": "Not folk-specific, but a major international showcase opportunity with an online application.",
        "source_url": "https://sxsw.com/apply/showcase-applications/",
        "form_fields": make_fields(bio_words=150, ask_press=True, genre_options=["Folk", "Americana", "Indie", "Rock", "World", "Electronic", "Hip-hop", "Other"]),
    },
]
